/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DeliverablesRouteImport } from './routes/deliverables'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverablesRoute = DeliverablesRouteImport.update({
  id: '/deliverables',
  path: '/deliverables',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deliverables': typeof DeliverablesRoute
  '/forecast': typeof ForecastRoute
  '/methodology': typeof MethodologyRoute
  '/references': typeof ReferencesRoute
  '/requirements': typeof RequirementsRoute
  '/scenarios': typeof ScenariosRoute
  '/simulator': typeof SimulatorRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deliverables': typeof DeliverablesRoute
  '/forecast': typeof ForecastRoute
  '/methodology': typeof MethodologyRoute
  '/references': typeof ReferencesRoute
  '/requirements': typeof RequirementsRoute
  '/scenarios': typeof ScenariosRoute
  '/simulator': typeof SimulatorRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deliverables': typeof DeliverablesRoute
  '/forecast': typeof ForecastRoute
  '/methodology': typeof MethodologyRoute
  '/references': typeof ReferencesRoute
  '/requirements': typeof RequirementsRoute
  '/scenarios': typeof ScenariosRoute
  '/simulator': typeof SimulatorRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/deliverables'
    | '/forecast'
    | '/methodology'
    | '/references'
    | '/requirements'
    | '/scenarios'
    | '/simulator'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/deliverables'
    | '/forecast'
    | '/methodology'
    | '/references'
    | '/requirements'
    | '/scenarios'
    | '/simulator'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/deliverables'
    | '/forecast'
    | '/methodology'
    | '/references'
    | '/requirements'
    | '/scenarios'
    | '/simulator'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DeliverablesRoute: typeof DeliverablesRoute
  ForecastRoute: typeof ForecastRoute
  MethodologyRoute: typeof MethodologyRoute
  ReferencesRoute: typeof ReferencesRoute
  RequirementsRoute: typeof RequirementsRoute
  ScenariosRoute: typeof ScenariosRoute
  SimulatorRoute: typeof SimulatorRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliverables': {
      id: '/deliverables'
      path: '/deliverables'
      fullPath: '/deliverables'
      preLoaderRoute: typeof DeliverablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DeliverablesRoute: DeliverablesRoute,
  ForecastRoute: ForecastRoute,
  MethodologyRoute: MethodologyRoute,
  ReferencesRoute: ReferencesRoute,
  RequirementsRoute: RequirementsRoute,
  ScenariosRoute: ScenariosRoute,
  SimulatorRoute: SimulatorRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
